### ISSUE TITLE
What API Key for Rovi is to be used

### ISSUE THREAD

**Issue by pr3tty8oyfl0yd** [sfanous/SmoothStreamsEPGGenerator#1]
When signing up for Rovi which of the three keys they provide is supposed to be used?

**Comment by sfanous** [comment]
I'm only aware of 2 keys
API Key & Shared Secret

api_key = API Key
shared_secret = Shared Secret

**Comment by pr3tty8oyfl0yd** [comment]
Yes there are two keys but there are 3 separate sets of keys.

1. Auto complete
    A. Key
    B. Secret

2. MetaData and Search
   A. Key
   B. Secrete

3. TV Listings
    A. Just an API key no secrete


The one I would have assumed I use would have been the TV Listing key however as you can see there is no shared secrete key with the api key for that one?

Any idea??


Floyd Banner

**Comment by sfanous** [comment]
I'm not sure about all these keys. Here's what my Rovi/TiVo account looks like

[https://imgur.com/f1YB5ff](url)

I map the API Key value to api_key and the Shared Secret value to shared_secret
